### ISSUE TITLE
Figure out MVC stuff

### ISSUE THREAD

**Issue by nocduro** [CMPUT301F17T21/StylePoints#18]
Figure out how to structure the project so it is model view controller. In a meeting with the TA they said that the controller should be a singleton class.

I don't have much experience with this, but from the lab presentation it looks like we might have to modify our UML to use interfaces like `Observable`, `Observer`

**Comment by nocduro** [comment]
Talked with the TA today about our UML/design pattern stuff.

He said we need to basically redo our UML to use MVC pattern, and that he doesn't care too much about the UI or activities, and cares mostly about the architecture/design pattern we are using. 

Instead of our `HabitType` containing a list of `HabitEvents` we instead abstract the list of these to be in the controller. The controller should be a Singleton class, he said something about Boundary classes (?) from the lecture notes for something else too.

We also need to use `Observer` and `Observable` interfaces on our classes (check pattern lab presentation).

He said we should have this updated by next Tuesday so that we can get feedback on the new UML.

Finally, he said we have to come to the lab to do the weekly team meetings (unless sick, or otherwise can't come). I was the only one here for the team meeting today...

@nikosomos @aseth99 @BradHanasyk @kevin3567

**Comment by nocduro** [comment]
This site may be useful for the architecture stuff: https://developer.android.com/topic/libraries/architecture/index.html

**Comment by kevin3567** [comment]
A revised uml, based on Mvc is added. Note that it is rudimentary; if there
is any errors or improvements, please notify me. Otherwise, barring the
group meeting, I will resume work on the app after Thursday noon (for exam
reasons).
