### ISSUE TITLE
Create local storage for User

### ISSUE THREAD

**Issue by nocduro** [CMPUT301F17T21/StylePoints#24]
https://github.com/CMPUT301F17T21/StylePoints/wiki/Architecture-Plan
https://github.com/CMPUT301F17T21/StylePoints/wiki/Profile-Requirements

Not sure if we called this `User` or `Profile`. Should be a similar layout as the `HabitEvent` local storage checklist seen in #22 

Ideas:
* Should have a unique id based on the phone hardware
* Created on first app startup after user signs up with a username (no password needed I think..)
* Should we store other users locally (people we follow) or just ourselves? If just our self we probably don't need to use a database for it...

Currently blocked while we figure out how the local storage should work in #23

**Comment by nikosomos** [comment]
Couple of questions for this one. The UserEntity should only need a username and Id field right? If yes then do we have to make a habit have a foreign key to relate to a user?

**Comment by nocduro** [comment]
> habit have a foreign key to relate to a user

I think our local sqlite database will only ever hold our local users habits/events so we wouldn't need the foreign key, we can assume they belong to the local user. Of course, when we go to upload that to elastic search we will have to add our userId to store it

**Comment by nikosomos** [comment]
Adding to this issue to create a first time login page. This seems like an alright way to do this:
https://stackoverflow.com/questions/7238532/how-to-launch-activity-only-once-when-app-is-opened-for-first-time
