### ISSUE TITLE
Release Planning

### ISSUE THREAD

**Issue by nocduro** [CMPUT301F17T21/StylePoints#3]
> Plan the major use cases and user stories that need to be done for project part 4, and what will be deferred until later for project part 5. This plan will likely evolve and should be maintained up-to-date in your team wiki. This will be used to help track progress on completing the requirements.

**Comment by nocduro** [comment]
Wiki link: https://github.com/CMPUT301F17T21/StylePoints/wiki/Release-Planning

I currently split this up into doing all of the profile and habit related stuff for part 4 (see [requirements](https://github.com/CMPUT301F17T21/StylePoints/wiki/Requirements)), and the social stuff, and geolocation for part 5. Should we do the picture related stuff in part 5 as well?

**Comment by nikosomos** [comment]
Anyone want to look over the release planning to make sure its realistic?

**Comment by nocduro** [comment]
Project Part 4 is due on November 13th, so the planned completion dates should be on our before then (for part 4). Other than that it looks pretty good to me!

**Comment by nikosomos** [comment]
The ones that extend past that date do so because they might change with the changes to some of the project 5 additions so they would still be in development.

**Comment by nocduro** [comment]
> The ones that extend past that date do so because they might change with the changes to some of the project 5 additions so they would still be in development.

Ok, sounds good 👍
