### ISSUE TITLE
Get Event for Today

### ISSUE THREAD

**Issue by kevin3567** [CMPUT301F17T21/StylePoints#38]
Based on the habit schedule, the event which should be completed for today should be retrieved, and listed on the main_activity. This not yet implemented.

**Comment by nocduro** [comment]
We don't want the event, we want habits that are scheduled for today. I'm working on this right now, check out the `room-arch-mack` branch for my progress. I've now made a nicer implementation for storing the schedule in the database.

**Comment by kevin3567** [comment]
Okay, thanks. I will work on taking photos. By the way, did the professor
reply regarding the SQLite?

**Comment by nocduro** [comment]
> By the way, did the professor reply regarding the SQLite?

No response yet :(

I think we move forward with the database so we have something for tomorrow, and if they say we can't use it then change over for part 5 deadline.

**Comment by kevin3567** [comment]
I suppose, although they did say that we are not to use SQLite without
explicit permission. Just out of curiosity, in case the professor gives a
last minute announcement, if the database has to be changed, how long would
it take?

**Comment by kevin3567** [comment]
The photo taking is working, how should I save the image? I m currently
considering on converting it from Bitmap to Byte. Would that work?

**Comment by nocduro** [comment]
Got something to work in f2ad7d6
